[YAPPIOS-110] 사진 상세 페이지 디자인 작업 완료
YAPP-19th/Minning-iOS pull request #28
Opened 2021-11-20 15:35 UTC by koserim

## 개요
* 사진 상세 페이지 디자인 작업
* 사진 그리드 페이지의 사진 데이터를 사진 상세 페이지에 전달

## TO-DO
* 그룹 상세 페이지 구현 완료 후, 사진 그리드, 사진 상세 페이지 연결 필요 (일단 present 해서 디자인 확인 중입니다,,)

2021-11-20 17:04 UTC, glossyyoon approved these changes
수고하셨습니다 :-) !! 👍 👍

2021-11-20 17:04 UTC, glossyyoon commented on Minning/ViewControllers/Main/Group/GroupDetail/PhotoDetail/PhotoDetailViewModel.swift
> +        selectedPhotoIndex.accept(selectedPhotoIndex.value + 1)
accept는 세림님이 만드신 함수인가요?!

2021-11-21 23:37 UTC, della-padula commented on Minning/ViewControllers/Main/Group/GroupDetail/PhotoDetail/PhotoDetailViewModel.swift
> +        selectedPhotoIndex.accept(selectedPhotoIndex.value + 1)
DataBinding에 정의되어 있는 함수입니다... command 누르고 definition 들어가보셔요

2021-11-21 23:38 UTC, della-padula requested changes
버전 분기 처리 부분만 수정해주시면 될 것 같슴다

2021-11-21 23:38 UTC, della-padula commented on DesignSystem/DesignSystem/CustomView/PlainUINavigationBar.swift
> +        if #available(iOS 13.0, *) {
우리 deploy target 13.0이라서 이 부분 지워도 될 것 같아요

2021-11-26 11:59 UTC, koserim commented on DesignSystem/DesignSystem/CustomView/PlainUINavigationBar.swift
> +        if #available(iOS 13.0, *) {
수정 후 반영했습니다. 감사합니다~

2021-11-26 12:35 UTC, della-padula approved these changes

2021-11-26 12:35 UTC, merged