[YAPPIOS-177] AddViewController 디자인 수정, iOS15대응
YAPP-19th/Minning-iOS pull request #35
Opened 2021-12-01 05:29 UTC by glossyyoon

<img width="346" alt="스크린샷 2021-12-01 오후 2 28 02" src="https://user-images.githubusercontent.com/39082599/144177145-2620bb84-3040-4c6b-bd1a-78505357ac6d.png">

AddViewController 디자인 수정하였습니다 !

2021-12-02 13:21 UTC, della-padula requested changes
주석 부분 코멘트 확인해주세요~

2021-12-02 13:21 UTC, della-padula commented on Minning/ViewControllers/Main/Home/Add/AddViewController.swift
> +//        stackView.addArrangedSubview(categoryStackView)
여기 주석 부분은 추후 사용할 예정인 코드인가요?

2021-12-03 07:20 UTC, glossyyoon commented on Minning/ViewControllers/Main/Home/Add/AddViewController.swift
> +//        stackView.addArrangedSubview(categoryStackView)
아닙니다 지워서 다시 올리겠습니닷

2021-12-08 03:07 UTC, della-padula approved these changes

2021-12-08 03:07 UTC, merged