[YAPPIOS-199] 홈 루틴 api 적용 중간 PR
YAPP-19th/Minning-iOS pull request #45
Opened 2021-12-15 15:23 UTC by koserim

## 변경사항
* 루틴 추가 api 적용
* 순서편집 페이지로 홈탭의 루틴 정보 전달
* 순서 편집 api 적용

## TODO
* 명언 작성 api 적용 완료 후 루틴 달성률 설정 api 적용 
* 현재 루틴 추가 시 선택된 카테고리 무조건 자기개발로만 보내고 있어서 카테고리 2개 이상 선택되지 않도록 수정 필요

2021-12-15 16:13 UTC, della-padula requested changes

2021-12-15 16:13 UTC, della-padula commented on Minning/Network/MinningAPIModel.swift
> +        case 0:
이 부분은 Category(rawValue: categoryValue) ?? .other 이렇게 하는 건 어떨까요?
enum이라서 저렇게 하면 어떨까 싶은데..

2021-12-15 16:13 UTC, della-padula commented on Minning/ViewControllers/Main/Home/Add/AddDayView.swift
>          dayLabel.font = .font14P
43, 44줄은 20-22줄 안에 넣어도 될 것 같아요 :)

2021-12-16 15:56 UTC, koserim commented on Minning/Network/MinningAPIModel.swift
> +        case 0:
맞아요 
뇌 빼고하다가 그만...
감사합니다~~ 수정했습니다

2021-12-16 15:56 UTC, koserim commented on Minning/ViewControllers/Main/Home/Add/AddDayView.swift
>          dayLabel.font = .font14P
수정했습니다!

2021-12-17 01:19 UTC, della-padula approved these changes

2021-12-17 01:19 UTC, merged